---
# Configure tasks. Here most of the variables should come from 'defaults/main.yml'
# Pay atention to the use of tags!

# Example create folders ...
- name: Create the ssl folder
  file:
    path: "{{ rolename_ssl_dir }}"
    owner: "{{ rolename_user }}"
    group: "{{ rolename_group }}"
    mode: 0750
    state: directory
  when: rolename_ssl
  tags: ["ssl"]


# Example, copy some local files. Also, have a look at the template.
- name: Copy the ssl certificates
  copy:
    src: "{{ item }}"
    dest: "{{ rolename_ssl_dir }}/{{ item | basename }}"
    owner: "{{ rolename_user }}"
    group: "{{ rolename_group }}"
    mode: 0640
  with_items:
    - "{{ rolename_ssl_cacertfile }}"
    - "{{ rolename_ssl_certfile }}"
  when: rolename_ssl
  tags: ["ssl"]


- name: Generate the main configuration file
  template:
    src: rolename.config.j2
    dest: "{{ rolename_config }}"
    owner: "{{ rolename_user }}"
    group: "{{ rolename_group }}"
    mode: 0644
  notify: restart rolename
  register: __rolename_updated_conf


# Maybe it is not needed ... but the purpose is the same as
# in 'install.yml' when packages are installed ..
- name: Checking if configuration was updated
  set_fact: >
    _rolename_updated="{{ __rolename_updated_conf.changed }}"


# Now is time to start the service!!
- name: Ensure service is started and enabled on boot
  service: 
    name: "{{ rolename_daemon }}"
    state: started 
    enabled: "{{ rabbitmq_enabled_on_startup | ternary('yes', 'no') }}"

